// Generated by scripts/build-illustration-map.R (pre-render hook). Do not edit.
window.ILLUS_MAP = {
  "fig01": {"src": "content/data-public/raw/figures/ai-communication-model.png", "desc": "Human-LLM communication model"},
  "fig02": {"src": "content/data-public/raw/figures/Blind_men_and_elephant3.jpg", "desc": "Blind men and an elephant"},
  "fig03": {"src": "content/data-public/raw/figures/chambers-2008.jpg", "desc": "Chambers (2008), Software for Data Analysis"},
  "fig04": {"src": "content/data-public/raw/figures/dialectic-epistemology.jpg", "desc": "Dialectic epistemology for research analytics"},
  "fig05": {"src": "content/data-public/raw/figures/dialects-data-expression.jpg", "desc": "Dialects of data expression"},
  "fig06": {"src": "content/data-public/raw/figures/yeg-3-years.gif", "desc": "Edmonton orthophoto, 2022 to 2024"},
  "fig07": {"src": "content/data-public/raw/figures/yeg-51-zoom.gif", "desc": "Edmonton orthophoto, concentric zoom"},
  "responsibilities-g1": {"src": "content/analysis/responsibilities/g1-ds-lifecycle/g1-ds-lifecycle.png", "desc": "Data science project lifecycle"}
};
